catalogue/catalogue/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('', include('mainapp.urls')),
]

catalogue/mainapp/urls.py
from django.urls import path
from .views import (
    ArticleDetail, AuthorDetail, ArticlesList, AuthorsList,
    ArticleCreate, home
    )


urlpatterns = [
    path('', home, name='home'),
    path('article/<int:pk>/', ArticleDetail.as_view(), name='article'),
    path('article/', ArticlesList.as_view(), name='articles'),
    path('author/<int:pk>/', AuthorDetail.as_view(), name='author'),
    path('author/', AuthorsList.as_view(), name='authors'),
    path('article/create/', ArticleCreate.as_view(), name='article_create'),
]

catalogue/mainapp/models.py
from django.db import models
from django.db.models import CharField, TextField, ManyToManyField
from django.urls import reverse


class Author(models.Model):

    first_name = CharField(max_length=30, verbose_name='Имя')
    last_name = CharField(max_length=30, verbose_name='Фамилия')

    class Meta:

        ordering = ['first_name']
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def get_absolute_url(self) -> str:
        return reverse('author', args=[self.pk])

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'


class Article(models.Model):

    title = CharField(max_length=255, verbose_name='Заголовок')
    text = TextField(verbose_name='Текст')
    authors = ManyToManyField(Author, verbose_name='Авторы')

    class Meta:

        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def get_absolute_url(self) -> str:
        return reverse('article', args=[self.pk])

    def __str__(self) -> str:
        return self.title

catalogue/mainapp/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, CreateView
from .models import Article, Author


class AuthorDetail(DetailView):

    model = Author


class AuthorsList(ListView):

    model = Author


class ArticleDetail(DetailView):

    model = Article


class ArticlesList(ListView):

    queryset = Article.objects.prefetch_related('authors')


class ArticleCreate(CreateView):

    model = Article
    fields = ['title', 'text', 'authors']


def home(request):
    return redirect('articles', permanent=True)

catalogue/mainapp/templates/mainapp/article_detail.html
{% extends 'mainapp/index.html' %}
{% block main %}
  <h3>{{ article.title }}</h3>
  <text>{{ article.text }}</text>
  <h4>Авторы:</h5>
  <ul>
    {% for i in article.authors.all %}
      <li><a href="{{ i.get_absolute_url }}">{{ i }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

catalogue/mainapp/templates/mainapp/article_form.html
{% extends 'mainapp/index.html' %}
{% block main %}
  <form method="POST" action="{% url 'article_create' %}">
    {% csrf_token %}
    <table>
      {{ form }}
    </table>
    <button type="submit">Добавить</button>
  </form>
{% endblock %}

catalogue/mainapp/templates/mainapp/article_list.html
{% extends 'mainapp/index.html' %}
{% block styles %}
<style>
  #authors li{
    display: inline;
  }
  .article_title{
    font-size: larger;
  }
</style>
{% endblock %}
{% block main %}
  {% for i in article_list %}
    <a href="{{ i.get_absolute_url }}" class="article_title">{{ i.title }}</a>
    <ul id="authors">
      <li>Авторы:</li>
      {% for j in i.authors.all %}
      <li><a href="{{ j.get_absolute_url }}">{{ j }}</a></li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endblock %}

catalogue/mainapp/templates/mainapp/author_detail.html
{% extends 'mainapp/index.html' %}
{% block main %}
  <h3>{{ author }}</h5>
  <h4>Статьи:</h4>
  <ul>
  {% for i in author.article_set.all %}
    <li><a href="{{ i.get_absolute_url }}">{{ i.title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

catalogue/mainapp/templates/mainapp/author_list.html
{% extends 'mainapp/index.html' %}
{% block main %}
  <ul>
  {% for i in author_list %}
    <li><a href="{{ i.get_absolute_url }}">{{ i }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

catalogue/mainapp/templates/mainapp/header.html
{% block styles %}
  <style>
      #navbar li{
          display: inline;
          font-size: xx-large;
      }
  </style>
{% endblock %}
<ul id="navbar">
  <li><a href="{% url 'articles' %}">Статьи</a></li>
  <li><a href="{% url 'authors' %}">Авторы</a></li>
  <li><a href="{% url 'article_create' %}">Создать статью</a></li>
</ul>

catalogue/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    {% block styles %}
    {% endblock %}
  </head>
  <body>
    <header>
      {% include 'mainapp/header.html' %}
    </header>
    <main></main>
      {% block main %}
      {% endblock %}
    </main>
  </body>
</html>